# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"


  MasterCount = 1

  # Kubernetes Master Nodes
  (1..MasterCount).each do |i|
    config.vm.define "k8s-master" do |masternode|
      masternode.vm.box = "centos/7"
      masternode.vm.hostname = "k8s-master"
      masternode.vm.network "private_network", ip: "192.168.1.10"
      masternode.vm.provider "virtualbox" do |v|
        v.name = "k8s-master"
        v.memory = 4096
        v.cpus = 2
      end
    end
  end

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "k8s-node#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "k8s-node1#{i}"
      workernode.vm.network "private_network", ip: "192.168.1.1#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "k8s-node#{i}"
        v.memory = 4096
        v.cpus = 3
      end
    end
  end

end
