# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  NodeCount = 2

  # Kubernetes Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "k8s-node#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "k8s-node#{i}"
      workernode.vm.network "private_network", ip: "192.168.1.1#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "k8s-node#{i}"
        v.memory = 2048
        v.cpus = 2
      end
    end
  end

end
